---
- name: Initialize Docker Swarm
  command: docker swarm init
  when: ansible_facts['docker_swarm'] is not defined or ansible_facts['docker_swarm'] is none

- name: Deploy Yii2 app as a Docker Swarm service
  community.docker.docker_swarm_service:
    name: yii2-app
    image: siddocker467/basic-yii2-app:latest
    publish:
      - published_port: 8080   # Host port
        target_port: 9000      # Container port
        protocol: tcp
    state: present
    force_update: true

