---
- name: Install PHP and necessary extensions
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - php{{ php_version }}-fpm
    - php{{ php_version }}-cli
    - php{{ php_version }}-mysql
    - php{{ php_version }}-gd
    - php{{ php_version }}-curl
    - php{{ php_version }}-mbstring
