---
- name: Install NGINX
  dnf:
    name: nginx
    state: present


- name: Copy NGINX reverse proxy config
  copy:
    src: default.conf
    dest: /etc/nginx/nginx.conf


- name: restart nginx
  service:
    name: nginx
    state: restarted
