---
- name: Install NGINX
  apt:
    name: nginx
    state: present

- name: Configure NGINX as reverse proxy for Yii2 app
  template:
    src: nginx/default.conf
    dest: /etc/nginx/sites-available/default
  notify:
    - restart nginx

- name: Ensure NGINX is running
  service:
    name: nginx
    state: started
    enabled: yes
