name: CI/CD to Docker Swarm

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Get latest image tag
      id: get_tag
      run: |
        IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/basic-yii2-app"
        TAGS=$(curl -s https://hub.docker.com/v2/repositories/${{ secrets.DOCKERHUB_USERNAME }}/basic-yii2-app/tags?page_size=100 | jq -r '.results[].name' | grep -E '^[0-9]+$' || echo "0")
        LATEST=$(echo "$TAGS" | sort -n | tail -n 1)
        NEXT=$((LATEST + 1))
        echo "next_tag=$NEXT" >> $GITHUB_OUTPUT

    - name: Build and tag Docker image
      run: |
        IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/basic-yii2-app"
        docker build -t $IMAGE_NAME:${{ steps.get_tag.outputs.next_tag }} -t $IMAGE_NAME:latest docker/Dockerfile

    - name: Push Docker images
      run: |
        IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/basic-yii2-app"
        docker push $IMAGE_NAME:${{ steps.get_tag.outputs.next_tag }}
        docker push $IMAGE_NAME:latest

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Update Docker Swarm service
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/basic-yii2-app:latest
          docker service update --image ${{ secrets.DOCKERHUB_USERNAME }}/basic-yii2-app:latest yii2-app
        EOF
